#!/usr/bin/expect
set timeout 20
set ip [lindex $argv 0]
set port [lindex $argv 1]
set user [lindex $argv 2]
set password [lindex $argv 3]

spawn ssh $ip -p $port -l $user
#expect "'^]'."
#sleep .1;
expect  "$user@$ip's password:"
send "$password\n";
interact


