#!/bin/bash
BASE=/srv/repos
#set -e
DIRS=$(find ${BASE} -maxdepth 1 -type d)

async_call(){
    local DIR=$1
    shift
    RET=$(cd $DIR;"${@}" 2>&1)
    RC=$?
    echo -e "\n\033[36m$DIR:\033[0m\n$RET"
    return $RC
}

pids=()
out=()
count=0
for d in $DIRS; do
    if [ "${d}" != "${BASE}" ];then
        out[$count]=$(async_call $d "${@}" &)
        pids+=( $! )
    fi
    let count+=1
done

for pid in ${pids[@]}; do
    wait $pid
done

echo -e "${out[@]}"
