#!/usr/bin/env bash
IMAGE=$1
docker history $IMAGE  --no-trunc --human=true --format "{{.CreatedBy}}" | tail -n 1000 -r | \
    sed -e 's|/bin/sh -c #(nop)  ||g' \
        -e 's|/bin/sh -c #(nop) ||g' \
        -e 's|/bin/sh -c|RUN|g'
